//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHailingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRide
    {
        public int RId { get; set; }
        public Nullable<int> Driver { get; set; }
        public Nullable<int> Passenger { get; set; }
        public string RequestLocation { get; set; }
        public string Destination { get; set; }
        public string vehicle { get; set; }
        public string Rent { get; set; }
        public string shift { get; set; }
    
        public virtual tblDriver tblDriver { get; set; }
        public virtual tblPassenger tblPassenger { get; set; }
    }
}
